#!/usr/bin/env swift
// Embed assets/brands/*.png into Sources/ShotScribeUI/BrandArtData.swift as
// base64, so the marks ship inside the binary and need no resource bundle
// (scripts/package-app.sh copies only the executable and the icns).
//
//   cd <repo root>
//   DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer \
//     swiftc -o .build/make-brand-art scripts/make-brand-art.swift && .build/make-brand-art
import Foundation

let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
let dir = root.appendingPathComponent("assets/brands")
let out = root.appendingPathComponent("Sources/ShotScribeUI/BrandArtData.swift")
let names = ["claude", "codex", "gemini", "cursor", "ollama"]
// Marks drawn in a single colour; the app renders them as templates so they
// take the tile's foreground. A `<name>.mono` file beside the PNG says so.
var entries: [String] = []
var mono: [String] = []
for name in names {
    let file = dir.appendingPathComponent("\(name).png")
    guard let data = try? Data(contentsOf: file) else { continue }
    entries.append("        \"\(name)\": \"\(data.base64EncodedString())\",")
    let isMono = FileManager.default.fileExists(atPath: dir.appendingPathComponent("\(name).mono").path)
    if isMono { mono.append("\"\(name)\"") }
    print("embedded \(name).png (\(data.count) bytes)" + (isMono ? ", monochrome" : ""))
}
let literal = entries.isEmpty ? "[:]" : "[\n\(entries.joined(separator: "\n"))\n    ]"
let swift = """
// Generated by scripts/make-brand-art.swift from assets/brands/*.png. Do not edit.
enum BrandArtData {
    static let png: [String: String] = \(literal)
    /// Marks drawn in one colour, rendered as templates.
    static let monochrome: Set<String> = [\(mono.joined(separator: ", "))]
}

"""
try! swift.write(to: out, atomically: true, encoding: .utf8)
print("wrote \(out.lastPathComponent) with \(entries.count) mark(s)")
