#!/usr/bin/env swift
// Embed assets/brands/*.png into Sources/ShotScribeUI/BrandArtData.swift as
// base64, so the marks ship inside the binary and need no resource bundle
// (scripts/package-app.sh copies only the executable and the icns).
import Foundation

let root = URL(fileURLWithPath: CommandLine.arguments.first.map { ($0 as NSString).deletingLastPathComponent } ?? ".")
    .appendingPathComponent("..").standardized
let dir = root.appendingPathComponent("assets/brands")
let out = root.appendingPathComponent("Sources/ShotScribeUI/BrandArtData.swift")
let names = ["claude", "codex", "gemini", "cursor", "ollama"]
var entries: [String] = []
for name in names {
    let file = dir.appendingPathComponent("\(name).png")
    guard let data = try? Data(contentsOf: file) else { continue }
    entries.append("    \"\(name)\": \"\(data.base64EncodedString())\",")
    print("embedded \(name).png (\(data.count) bytes)")
}
let literal = entries.isEmpty ? "[:]" : "[\n\(entries.joined(separator: "\n"))\n    ]"
let swift = """
// Generated by scripts/make-brand-art.swift from assets/brands/*.png. Do not edit.
enum BrandArtData {
    static let png: [String: String] = \(literal)
}

"""
try! swift.write(to: out, atomically: true, encoding: .utf8)
print("wrote \(out.lastPathComponent) with \(entries.count) mark(s)")
